### ISSUE TITLE
Using an endpoint planned for deprecation

### ISSUE THREAD

**Issue by jacobbednarz** [thcp/cloudflare-analytics#8]
Thanks for creating this! It looks 🆒!

Perusing the source, I noticed you're using [an endpoint](https://github.com/thcp/cloudflare-analytics/blob/master/app/config.ini#L14) that is [scheduled for deprecation](https://api.cloudflare.com/deprecations). There is a newer GraphQL endpoint that is superseding this one which is quite a bit more efficient for querying analytics on larger zones. Here is also a [migration guide](https://developers.cloudflare.com/analytics/migration-guides/zone-analytics) if you're looking for a step-by-step overview of how to make the change.

**Comment by thcp** [comment]
Hi @jacobbednarz thanks for the heads up and your time on checking. Update is already under way and I expect to be pushing the changes before the deprecation.

**Comment by wongchikeung77** [comment]
@thcp  
Thanks 
Is there any further information ?

**Comment by thcp** [comment]
Hi @wongchikeung77 , yes due time constraints I wasn't' able to perform any update on this project. While I do have locally the updates with the new API, I'm scheduling to push the changes later this week.

**Comment by thcp** [comment]
@jacobbednarz / @wongchikeung77  Changes published to master branch. Grafana dashboard changes are pending but a simple/base template for deployment on k8s was added .
